---
title: "pokemonplots"
author: "Priya Singh Collins"
date: "5/5/2022"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
pokemondata <- readr::read_csv(here::here("data", "pokemon.csv"))
```

### First, move name, height and weight columns to front of dataset for easy access.
```{r}
pokemondata <- pokemondata |>
  select(name, height_m, weight_kg, everything())

pokemondata
```

### Filter and summarize data for legendary pokemon
```{r}
pd_legendary <- pokemondata |>
  select(name, height_m, weight_kg, capture_rate, is_legendary) |>
  filter(is_legendary != 0)

cap_rate_leg <- factor(pd_legendary$capture_rate)
cap_rate_leg <- as.numeric(cap_rate_leg)

height_m_leg <- pd_legendary |>
  summarize(mean(height_m, na.rm = TRUE))

weight_kg_leg <- pd_legendary |>
  summarize(mean(weight_kg, na.rm = TRUE))

cap_rate_leg <- pd_legendary |>
  summarize(mean(cap_rate_leg, na.rm = TRUE))

print(height_m_leg)
print(weight_kg_leg)
print(cap_rate_leg)
```

### Filter and summarize data for non-legendary pokemon
```{r}
pd_notlegendary <- pokemondata |>
  select(name, height_m, weight_kg, capture_rate, is_legendary) |>
  filter(is_legendary == 0)

cap_rate_nleg <- factor(pd_notlegendary$capture_rate)
cap_rate_nleg <- as.numeric(cap_rate_nleg)

height_m_nleg <- pd_notlegendary |>
  summarize(mean(height_m, na.rm = TRUE))

weight_kg_nleg <- pd_notlegendary |>
  summarize(mean(weight_kg, na.rm = TRUE))

cap_rate_nleg <- pd_notlegendary |>
  summarize(mean(cap_rate_nleg, na.rm = TRUE))

print(height_m_nleg)
print(weight_kg_nleg)
print(cap_rate_nleg)
```

```{r}
sp_hw <- ggplot(pd_legendary) +
  aes(x = height_m, y = weight_kg) +
  geom_point() +
  geom_smooth(method = lm)

sp_hw + labs(title = "Height to Weight Ratio of Legendary Pokemon",
             x = "Height in m", y = "Weight in kg")
```

```{r}
sp_wcr <- ggplot(pokemondata) +
  aes(x = weight_kg,
      y = as.numeric(capture_rate),
      fill = is_legendary,
      color = is_legendary,
      size = height_m) +
  geom_point()

sp_wcr + labs(title = "Correlation Between Weight and Capture Rate of Legendary and Non-Legendary Pokemon",
              x = "Weight in kg", y = "Capture Rate")
```
